using FluentAssertions;
using Jobuler.Domain.Groups;
using Jobuler.Infrastructure.Persistence.Configurations;
using Xunit;

namespace Jobuler.Tests.Groups;

public class GroupConfigurationTests
{
    [Theory]
    [InlineData("AutoGenerated", SchedulingMode.AutoGenerated)]
    [InlineData("auto_generated", SchedulingMode.AutoGenerated)]
    [InlineData("SelfService", SchedulingMode.SelfService)]
    [InlineData("self_service", SchedulingMode.SelfService)]
    public void ParseSchedulingMode_AcceptsCurrentAndLegacyValues(string value, SchedulingMode expected)
    {
        GroupConfiguration.ParseSchedulingMode(value).Should().Be(expected);
    }
}
