"use client";

import { useTranslations } from "next-intl";
import Modal from "@/components/Modal";
import type { SchedulingMode } from "@/components/groups/selfService/SchedulingModeSelector";

interface ModeWarningDialogProps {
  open: boolean;
  selectedMode: SchedulingMode;
  onConfirm: () => void;
  onCancel: () => void;
  isPending?: boolean;
}

/**
 * Confirmation dialog warning that the scheduling mode choice is permanent.
 * Shown after the user selects a mode and template in the group creation wizard,
 * requiring explicit acknowledgment before proceeding with group creation.
 */
export default function ModeWarningDialog({
  open,
  selectedMode,
  onConfirm,
  onCancel,
  isPending = false,
}: ModeWarningDialogProps) {
  const t = useTranslations("selfService.confirmDialog");
  const tMode = useTranslations("selfService.modeSelector");

  const modeLabel =
    selectedMode === "AutoGenerated" ? tMode("autoTitle") : tMode("selfServiceTitle");

  return (
    <Modal open={open} onClose={onCancel} title={t("title")} maxWidth={440}>
      <div className="space-y-5">
        {/* Warning icon and message */}
        <div className="flex flex-col items-center text-center gap-3">
          <div className="w-12 h-12 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
            <svg
              className="w-6 h-6 text-amber-600 dark:text-amber-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"
              />
            </svg>
          </div>

          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
            {t("message")}
          </p>

          {/* Selected mode badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-700">
            <span className="text-xs font-medium text-slate-600 dark:text-slate-300">
              {modeLabel}
            </span>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex gap-3">
          <button
            type="button"
            onClick={onCancel}
            disabled={isPending}
            className="flex-1 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 text-sm font-medium px-4 py-2.5 rounded-xl hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors disabled:opacity-50"
          >
            {t("cancel")}
          </button>
          <button
            type="button"
            onClick={onConfirm}
            disabled={isPending}
            className="flex-1 bg-sky-500 hover:bg-sky-600 text-white text-sm font-medium px-4 py-2.5 rounded-xl disabled:opacity-50 transition-colors"
          >
            {isPending ? (
              <span className="inline-flex items-center gap-2">
                <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                {t("confirm")}
              </span>
            ) : (
              t("confirm")
            )}
          </button>
        </div>
      </div>
    </Modal>
  );
}
