"use client";

import { useTranslations } from "next-intl";

export type SchedulingMode = "AutoGenerated" | "SelfService";

interface SchedulingModeSelectorProps {
  selectedMode: SchedulingMode | null;
  onSelect: (mode: SchedulingMode) => void;
}

/**
 * Scheduling mode selection step for the group creation wizard.
 * Presents two visual cards: "סידור אוטומטי" and "בחירת משמרות".
 * Displays a permanent warning and highlights the selected card.
 */
export default function SchedulingModeSelector({ selectedMode, onSelect }: SchedulingModeSelectorProps) {
  const t = useTranslations("selfService.modeSelector");

  const modes: Array<{
    id: SchedulingMode;
    titleKey: string;
    descriptionKey: string;
    icon: string;
    color: string;
  }> = [
    {
      id: "AutoGenerated",
      titleKey: "autoTitle",
      descriptionKey: "autoDescription",
      icon: "🤖",
      color: "#0ea5e9",
    },
    {
      id: "SelfService",
      titleKey: "selfServiceTitle",
      descriptionKey: "selfServiceDescription",
      icon: "🙋",
      color: "#8b5cf6",
    },
  ];

  return (
    <div className="space-y-4">
      <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-1.5">
        {t("title")}
      </label>

      {/* Mode cards */}
      <div className="grid grid-cols-1 gap-3">
        {modes.map((mode) => {
          const isSelected = selectedMode === mode.id;
          return (
            <button
              key={mode.id}
              type="button"
              onClick={() => onSelect(mode.id)}
              aria-pressed={isSelected}
              className={`text-start p-4 rounded-xl border-2 transition-all ${
                isSelected
                  ? "border-sky-500 bg-sky-50 dark:bg-sky-900/20 shadow-sm ring-2 ring-sky-200 dark:ring-sky-800"
                  : "border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600"
              }`}
            >
              <div className="flex items-start gap-3">
                <span
                  className="w-10 h-10 rounded-lg flex items-center justify-center text-lg flex-shrink-0"
                  style={{ background: `${mode.color}15` }}
                >
                  {mode.icon}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold text-slate-900 dark:text-white">
                    {t(mode.titleKey)}
                  </p>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
                    {t(mode.descriptionKey)}
                  </p>
                </div>
                {/* Selection indicator */}
                <div className="flex-shrink-0 mt-0.5">
                  <div
                    className={`w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors ${
                      isSelected
                        ? "border-sky-500 bg-sky-500"
                        : "border-slate-300 dark:border-slate-600"
                    }`}
                  >
                    {isSelected && (
                      <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </div>
                </div>
              </div>
            </button>
          );
        })}
      </div>

      {/* Permanent warning */}
      <div className="flex items-start gap-2 p-3 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800">
        <svg className="w-4 h-4 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
        </svg>
        <p className="text-xs text-amber-800 dark:text-amber-300 leading-relaxed">
          {t("permanentWarning")}
        </p>
      </div>
    </div>
  );
}
