using Jobuler.Domain.Common;

namespace Jobuler.Domain.Spaces;

public enum SpaceSpecialDayKind
{
    Holiday = 0,
    Weekend = 1,
    Custom = 2
}

public class SpaceSpecialDay : AuditableEntity, ITenantScoped
{
    public Guid SpaceId { get; private set; }
    public DateOnly Date { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public SpaceSpecialDayKind Kind { get; private set; }
    public decimal HomeLeaveWeightMultiplier { get; private set; }
    public bool RequiresCoverage { get; private set; } = true;
    public bool IsAutoGenerated { get; private set; }

    private SpaceSpecialDay() { }

    public static SpaceSpecialDay Create(
        Guid spaceId,
        DateOnly date,
        string name,
        SpaceSpecialDayKind kind,
        decimal homeLeaveWeightMultiplier = 1.5m,
        bool requiresCoverage = true,
        bool isAutoGenerated = false)
    {
        ValidateName(name);
        ValidateMultiplier(homeLeaveWeightMultiplier);

        return new SpaceSpecialDay
        {
            SpaceId = spaceId,
            Date = date,
            Name = name.Trim(),
            Kind = kind,
            HomeLeaveWeightMultiplier = homeLeaveWeightMultiplier,
            RequiresCoverage = requiresCoverage,
            IsAutoGenerated = isAutoGenerated
        };
    }

    public void Update(
        DateOnly date,
        string name,
        SpaceSpecialDayKind kind,
        decimal homeLeaveWeightMultiplier,
        bool requiresCoverage)
    {
        ValidateName(name);
        ValidateMultiplier(homeLeaveWeightMultiplier);

        Date = date;
        Name = name.Trim();
        Kind = kind;
        HomeLeaveWeightMultiplier = homeLeaveWeightMultiplier;
        RequiresCoverage = requiresCoverage;
        Touch();
    }

    private static void ValidateName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Special day name is required.");

        if (name.Trim().Length > 120)
            throw new ArgumentException("Special day name must be 120 characters or less.");
    }

    private static void ValidateMultiplier(decimal multiplier)
    {
        if (multiplier < 1m || multiplier > 5m)
            throw new ArgumentException("Home-leave weight multiplier must be between 1 and 5.");
    }
}
