import { describe, expect, test } from "vitest";
import {
  getSelfServiceTabBadges,
  getVisibleGroupTabs,
  SELF_SERVICE_ADMIN_TABS,
  SELF_SERVICE_MEMBER_TABS,
} from "../../app/groups/[groupId]/types";

describe("self-service group tab visibility", () => {
  test("members get the manual self-service workflow tabs without admin operations", () => {
    const tabs = getVisibleGroupTabs({
      schedulingMode: "SelfService",
      isAdmin: false,
    });

    expect(tabs).toEqual(SELF_SERVICE_MEMBER_TABS);
    expect(tabs).toEqual(
      expect.arrayContaining(["available-slots", "my-shifts", "waitlist", "swaps"])
    );
    expect(tabs).not.toContain("self-service-ops");
    expect(tabs).not.toContain("absence-reports");
    expect(tabs).not.toContain("self-service-config");
  });

  test("admins get the full manual self-service operating surface", () => {
    const tabs = getVisibleGroupTabs({
      schedulingMode: "SelfService",
      isAdmin: true,
    });

    expect(tabs).toEqual(SELF_SERVICE_ADMIN_TABS);
    expect(tabs).toEqual(
      expect.arrayContaining([
        "self-service-ops",
        "available-slots",
        "my-shifts",
        "waitlist",
        "swaps",
        "shift-templates",
        "self-service-config",
        "admin-overrides",
        "absence-reports",
      ])
    );
  });

  test("pending manual review count is surfaced on admin workflow tabs only", () => {
    expect(getSelfServiceTabBadges("SelfService", true, 4)).toEqual({
      "self-service-ops": 4,
      "absence-reports": 4,
    });

    expect(getSelfServiceTabBadges("SelfService", false, 4)).toEqual({});
    expect(getSelfServiceTabBadges("AutoGenerated", true, 4)).toEqual({});
  });

  test("auto-generated groups still hide admin-only tabs from members", () => {
    const memberTabs = getVisibleGroupTabs({
      schedulingMode: "AutoGenerated",
      isAdmin: false,
      allowMembersViewStats: false,
    });

    expect(memberTabs).toContain("schedule");
    expect(memberTabs).toContain("members");
    expect(memberTabs).not.toContain("tasks");
    expect(memberTabs).not.toContain("constraints");
    expect(memberTabs).not.toContain("roles");
    expect(memberTabs).not.toContain("settings");
    expect(memberTabs).not.toContain("stats");
  });

  test("auto-generated members can see stats only when the group allows it", () => {
    expect(
      getVisibleGroupTabs({
        schedulingMode: "AutoGenerated",
        isAdmin: false,
        allowMembersViewStats: true,
      })
    ).toContain("stats");
  });
});
