/**
 * Property-based tests for the pick group filter utility.
 *
 * Feature: shift-picker-lite
 * Task: 2.2 Write property test for group filtering
 *
 * **Validates: Requirements 2.1**
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import { filterSelfServiceGroups } from "../../lib/utils/pickGroupFilter";
import type { GroupWithMemberCountDto } from "../../lib/api/groups";

/**
 * Arbitrary that generates a random scheduling mode value,
 * including "SelfService", "AutoGenerated", undefined, and other random strings.
 */
const schedulingModeArb = fc.oneof(
  fc.constant("SelfService" as const),
  fc.constant("AutoGenerated" as const),
  fc.constant(undefined),
  fc.string({ minLength: 1, maxLength: 20 })
) as fc.Arbitrary<"AutoGenerated" | "SelfService" | undefined>;

/**
 * Arbitrary that generates a valid GroupWithMemberCountDto with a random schedulingMode.
 */
const groupArb: fc.Arbitrary<GroupWithMemberCountDto> = fc.record({
  id: fc.uuid(),
  name: fc.string({ minLength: 1, maxLength: 50 }),
  memberCount: fc.nat({ max: 200 }),
  solverHorizonDays: fc.nat({ max: 90 }),
  ownerPersonId: fc.option(fc.uuid(), { nil: null }),
  schedulingMode: schedulingModeArb,
});

/**
 * Arbitrary that generates a list of groups with mixed scheduling modes.
 */
const groupListArb = fc.array(groupArb, { minLength: 0, maxLength: 30 });

describe("Property 3: Group filtering preserves only self-service groups", () => {
  it("result contains exactly those groups with schedulingMode === 'SelfService' and no others", () => {
    fc.assert(
      fc.property(groupListArb, (groups) => {
        const result = filterSelfServiceGroups(groups);

        // Every group in the result must have schedulingMode === "SelfService"
        for (const group of result) {
          expect(group.schedulingMode).toBe("SelfService");
        }

        // Every group in the input with schedulingMode === "SelfService" must appear in the result
        const expectedIds = groups
          .filter((g) => g.schedulingMode === "SelfService")
          .map((g) => g.id);
        const resultIds = result.map((g) => g.id);

        expect(resultIds).toHaveLength(expectedIds.length);
        for (const id of expectedIds) {
          expect(resultIds).toContain(id);
        }

        // No group in the result has a different schedulingMode
        expect(result.every((g) => g.schedulingMode === "SelfService")).toBe(
          true
        );
      }),
      { numRuns: 100 }
    );
  });
});
