/**
 * Property-based tests for pickLastGroup utility.
 *
 * Feature: shift-picker-lite
 * Task: 1.3 Write property test for invalid last-group memory clearing
 *
 * **Validates: Requirements 3.2, 3.5**
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import { resolveLastGroup } from "../../lib/utils/pickLastGroup";
import type { GroupWithMemberCountDto } from "../../lib/api/groups";

/**
 * UUID v4 format regex (case-insensitive) — mirrors the one in pickLastGroup.ts.
 */
const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Arbitrary that generates a valid UUID v4 string.
 */
const uuidArb = fc.uuid();

/**
 * Arbitrary that generates a GroupWithMemberCountDto with a random UUID id.
 */
const groupArb = fc.record({
  id: uuidArb,
  name: fc.string({ minLength: 1, maxLength: 50 }),
  memberCount: fc.nat({ max: 100 }),
  solverHorizonDays: fc.nat({ max: 30 }),
  ownerPersonId: fc.option(uuidArb, { nil: null }),
  schedulingMode: fc.constantFrom(
    "AutoGenerated" as const,
    "SelfService" as const
  ),
});

/**
 * Arbitrary that generates a list of groups (0 to 10 groups).
 */
const groupsArb = fc.array(groupArb, { minLength: 0, maxLength: 10 });

/**
 * Arbitrary that generates strings that are NOT valid UUID format.
 * Filters out any string that accidentally matches UUID format.
 */
const nonUuidStringArb = fc
  .string({ minLength: 0, maxLength: 100 })
  .filter((s) => !UUID_REGEX.test(s));

describe("Property 2: Invalid last-group memory is cleared", () => {
  it("returns null for any string that is NOT a valid UUID format", () => {
    fc.assert(
      fc.property(nonUuidStringArb, groupsArb, (invalidStr, groups) => {
        const result = resolveLastGroup(invalidStr, groups);
        expect(result).toBeNull();
      }),
      { numRuns: 100 }
    );
  });

  it("returns null for any valid UUID that does NOT appear in the groups list", () => {
    fc.assert(
      fc.property(uuidArb, groupsArb, (uuid, groups) => {
        // Ensure the UUID is not in the groups list
        const groupsWithoutUuid = groups.filter((g) => g.id !== uuid);

        const result = resolveLastGroup(uuid, groupsWithoutUuid);
        expect(result).toBeNull();
      }),
      { numRuns: 100 }
    );
  });
});
