/**
 * Unit tests for the pick group filter utility.
 *
 * Feature: shift-picker-lite
 * Task: 2.1 Create group filtering utility for the picker
 *
 * **Validates: Requirements 2.1**
 */

import { describe, it, expect } from "vitest";
import { filterSelfServiceGroups } from "../../lib/utils/pickGroupFilter";
import type { GroupWithMemberCountDto } from "../../lib/api/groups";

function makeGroup(
  overrides: Partial<GroupWithMemberCountDto> & { id: string; name: string }
): GroupWithMemberCountDto {
  return {
    memberCount: 5,
    solverHorizonDays: 7,
    ownerPersonId: null,
    ...overrides,
  };
}

describe("filterSelfServiceGroups", () => {
  it("returns only groups with schedulingMode SelfService", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "Alpha", schedulingMode: "SelfService" }),
      makeGroup({ id: "2", name: "Beta", schedulingMode: "AutoGenerated" }),
      makeGroup({ id: "3", name: "Gamma", schedulingMode: "SelfService" }),
    ];

    const result = filterSelfServiceGroups(groups);

    expect(result).toHaveLength(2);
    expect(result.every((g) => g.schedulingMode === "SelfService")).toBe(true);
  });

  it("excludes groups with undefined schedulingMode", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "Alpha", schedulingMode: "SelfService" }),
      makeGroup({ id: "2", name: "Beta" }), // schedulingMode is undefined
    ];

    const result = filterSelfServiceGroups(groups);

    expect(result).toHaveLength(1);
    expect(result[0].id).toBe("1");
  });

  it("returns empty array when no groups are SelfService", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "Alpha", schedulingMode: "AutoGenerated" }),
      makeGroup({ id: "2", name: "Beta", schedulingMode: "AutoGenerated" }),
    ];

    const result = filterSelfServiceGroups(groups);

    expect(result).toHaveLength(0);
  });

  it("returns empty array for empty input", () => {
    const result = filterSelfServiceGroups([]);
    expect(result).toHaveLength(0);
  });

  it("sorts results by name ascending using Hebrew locale", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "גמא", schedulingMode: "SelfService" }),
      makeGroup({ id: "2", name: "אלפא", schedulingMode: "SelfService" }),
      makeGroup({ id: "3", name: "בטא", schedulingMode: "SelfService" }),
    ];

    const result = filterSelfServiceGroups(groups);

    expect(result[0].name).toBe("אלפא");
    expect(result[1].name).toBe("בטא");
    expect(result[2].name).toBe("גמא");
  });

  it("sorts English names alphabetically", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "Charlie", schedulingMode: "SelfService" }),
      makeGroup({ id: "2", name: "Alpha", schedulingMode: "SelfService" }),
      makeGroup({ id: "3", name: "Bravo", schedulingMode: "SelfService" }),
    ];

    const result = filterSelfServiceGroups(groups);

    expect(result[0].name).toBe("Alpha");
    expect(result[1].name).toBe("Bravo");
    expect(result[2].name).toBe("Charlie");
  });

  it("does not mutate the original array", () => {
    const groups: GroupWithMemberCountDto[] = [
      makeGroup({ id: "1", name: "Beta", schedulingMode: "SelfService" }),
      makeGroup({ id: "2", name: "Alpha", schedulingMode: "SelfService" }),
    ];
    const originalOrder = [...groups];

    filterSelfServiceGroups(groups);

    expect(groups[0].id).toBe(originalOrder[0].id);
    expect(groups[1].id).toBe(originalOrder[1].id);
  });
});
