using FluentAssertions;
using Jobuler.Application.Common;
using Jobuler.Application.Scheduling.Commands;
using Jobuler.Domain.Groups;
using Jobuler.Domain.Scheduling;
using Jobuler.Domain.Spaces;
using Jobuler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using NSubstitute;
using Xunit;

namespace Jobuler.Tests.Scheduling;

public class ChangeSchedulingModeCommandTests
{
    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new AppDbContext(options);
    }

    private static IPermissionService AllowAll()
    {
        var svc = Substitute.For<IPermissionService>();
        svc.RequirePermissionAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(Task.CompletedTask);
        return svc;
    }

    private static IPermissionService DenyAll()
    {
        var svc = Substitute.For<IPermissionService>();
        svc.RequirePermissionAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromException(new UnauthorizedAccessException("Permission denied.")));
        return svc;
    }

    [Fact]
    public async Task Handle_ChangesToSelfService_WhenNoActiveRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.SelfService);
    }

    [Fact]
    public async Task Handle_ChangesToAutoGenerated_WhenNoActiveRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_SameMode_IsNoOp()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act — should not throw
        await handler.Handle(command, CancellationToken.None);

        // Assert — still AutoGenerated
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_WithPendingRequests_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        // Status is Pending by default
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*unresolved requests*");
    }

    [Fact]
    public async Task Handle_WithApprovedRequests_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        shiftRequest.Approve();
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*unresolved requests*");
    }

    [Fact]
    public async Task Handle_WithOnlyCancelledRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        shiftRequest.Approve();
        shiftRequest.Cancel("No longer needed");
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_GroupNotFound_ThrowsKeyNotFound()
    {
        // Arrange
        using var db = CreateDb();
        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<KeyNotFoundException>();
    }

    [Fact]
    public async Task Handle_WithoutPermission_ThrowsUnauthorized()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, DenyAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<UnauthorizedAccessException>();
    }

    [Fact]
    public async Task Handle_InactiveGroup_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.Deactivate();
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*limited mode*");
    }
}
