using FluentAssertions;
using Jobuler.Application.Common;
using Jobuler.Application.Scheduling.Commands;
using Jobuler.Domain.Groups;
using Jobuler.Domain.Scheduling;
using Jobuler.Domain.Spaces;
using Jobuler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using NSubstitute;
using Xunit;

namespace Jobuler.Tests.Scheduling;

public class ChangeSchedulingModeCommandTests
{
    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new AppDbContext(options);
    }

    private static IPermissionService AllowAll()
    {
        var svc = Substitute.For<IPermissionService>();
        svc.RequirePermissionAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(Task.CompletedTask);
        return svc;
    }

    private static IPermissionService DenyAll()
    {
        var svc = Substitute.For<IPermissionService>();
        svc.RequirePermissionAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromException(new UnauthorizedAccessException("Permission denied.")));
        return svc;
    }

    [Fact]
    public async Task Handle_ChangesToSelfService_WhenNoActiveRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.SelfService);

        var config = await db.SelfServiceConfigs.SingleAsync(c => c.GroupId == group.Id);
        config.SpaceId.Should().Be(spaceId);
        config.MinShiftsPerCycle.Should().Be(0);
        config.MaxShiftsPerCycle.Should().Be(7);
        config.MaxAbsencesPerCycle.Should().Be(3);
        config.MaxLateCancellationsPerCycle.Should().Be(2);
        config.AllowMemberShiftClaims.Should().BeTrue();
        config.AllowWaitlist.Should().BeTrue();
    }

    [Fact]
    public async Task Handle_ChangesToSelfService_WhenConfigAlreadyExists_DoesNotOverwritePolicy()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        var existingConfig = SelfServiceConfig.Create(
            spaceId,
            group.Id,
            minShiftsPerCycle: 2,
            maxShiftsPerCycle: 4,
            requestWindowOpenOffsetHours: 96,
            requestWindowCloseOffsetHours: 12,
            cancellationCutoffHours: 18,
            maxLateCancellationsPerCycle: 1,
            lateCancellationWindowHours: 12,
            waitlistOfferMinutes: 30,
            cycleDurationDays: 14);
        existingConfig.SetAbsenceReportLimit(1);
        existingConfig.SetWorkflowPermissions(
            allowMemberShiftClaims: true,
            allowWaitlist: false,
            allowShiftChangeRequests: true,
            allowAbsenceReports: true,
            allowShiftSwaps: false);

        db.Groups.Add(group);
        db.SelfServiceConfigs.Add(existingConfig);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var configs = await db.SelfServiceConfigs.Where(c => c.GroupId == group.Id).ToListAsync();
        configs.Should().ContainSingle();
        configs[0].MinShiftsPerCycle.Should().Be(2);
        configs[0].MaxShiftsPerCycle.Should().Be(4);
        configs[0].MaxAbsencesPerCycle.Should().Be(1);
        configs[0].AllowWaitlist.Should().BeFalse();
        configs[0].AllowShiftSwaps.Should().BeFalse();
    }

    [Fact]
    public async Task Handle_ChangesToAutoGenerated_WhenNoActiveRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_SameMode_IsNoOp()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act — should not throw
        await handler.Handle(command, CancellationToken.None);

        // Assert — still AutoGenerated
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_WithPendingRequests_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        // Status is Pending by default
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*unresolved requests*");
    }

    [Fact]
    public async Task Handle_WithApprovedRequests_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        shiftRequest.Approve();
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*unresolved requests*");
    }

    [Fact]
    public async Task Handle_WithOnlyCancelledRequests_Succeeds()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        var shiftRequest = ShiftRequest.Create(
            spaceId, Guid.NewGuid(), Guid.NewGuid(), group.Id, Guid.NewGuid());
        shiftRequest.Approve();
        shiftRequest.Cancel("No longer needed");
        db.ShiftRequests.Add(shiftRequest);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.AutoGenerated);

        // Act
        await handler.Handle(command, CancellationToken.None);

        // Assert
        var updated = await db.Groups.FindAsync(group.Id);
        updated!.SchedulingMode.Should().Be(SchedulingMode.AutoGenerated);
    }

    [Fact]
    public async Task Handle_GroupNotFound_ThrowsKeyNotFound()
    {
        // Arrange
        using var db = CreateDb();
        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<KeyNotFoundException>();
    }

    [Fact]
    public async Task Handle_WithoutPermission_ThrowsUnauthorized()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, DenyAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<UnauthorizedAccessException>();
    }

    [Fact]
    public async Task Handle_InactiveGroup_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Test Group");
        group.Deactivate();
        db.Groups.Add(group);
        await db.SaveChangesAsync();

        var handler = new ChangeSchedulingModeCommandHandler(db, AllowAll());
        var command = new ChangeSchedulingModeCommand(spaceId, group.Id, Guid.NewGuid(), SchedulingMode.SelfService);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*limited mode*");
    }
}
