using FluentAssertions;
using Jobuler.Application.Scheduling;
using Jobuler.Application.Scheduling.Commands;
using Jobuler.Domain.Groups;
using Jobuler.Domain.Tasks;
using Jobuler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using NSubstitute;
using Xunit;

// Helper to create GroupTask with required parameters for tests

namespace Jobuler.Tests.Scheduling;

public class TriggerSolverSelfServiceGuardTests
{
    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new AppDbContext(options);
    }

    [Fact]
    public async Task Handle_SelfServiceGroup_ThrowsInvalidOperation()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Self-Service Group");
        group.SetSchedulingMode(SchedulingMode.SelfService);
        db.Groups.Add(group);

        // Add an active future task so the stale-task guard doesn't trigger first
        var groupTask = GroupTask.Create(
            spaceId, group.Id, "Task",
            DateTime.UtcNow.AddDays(-1), DateTime.UtcNow.AddDays(7),
            shiftDurationMinutes: 480, requiredHeadcount: 1,
            burdenLevel: TaskBurdenLevel.Normal, allowsDoubleShift: false,
            allowsOverlap: false, createdByUserId: Guid.NewGuid());
        db.GroupTasks.Add(groupTask);
        await db.SaveChangesAsync();

        var queue = Substitute.For<ISolverJobQueue>();
        var handler = new TriggerSolverCommandHandler(db, queue);
        var command = new TriggerSolverCommand(spaceId, "standard", Guid.NewGuid(), group.Id);

        // Act & Assert
        var act = () => handler.Handle(command, CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*SelfService*");
    }

    [Fact]
    public async Task Handle_AutoGeneratedGroup_DoesNotThrowSelfServiceError()
    {
        // Arrange
        using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var group = Group.Create(spaceId, null, "Auto Group");
        // Default is AutoGenerated
        db.Groups.Add(group);

        var groupTask = GroupTask.Create(
            spaceId, group.Id, "Task",
            DateTime.UtcNow.AddDays(-1), DateTime.UtcNow.AddDays(7),
            shiftDurationMinutes: 480, requiredHeadcount: 1,
            burdenLevel: TaskBurdenLevel.Normal, allowsDoubleShift: false,
            allowsOverlap: false, createdByUserId: Guid.NewGuid());
        db.GroupTasks.Add(groupTask);
        await db.SaveChangesAsync();

        var queue = Substitute.For<ISolverJobQueue>();
        var handler = new TriggerSolverCommandHandler(db, queue);
        var command = new TriggerSolverCommand(spaceId, "standard", Guid.NewGuid(), group.Id);

        // Act — should not throw the SelfService error (may throw other errors due to missing data, but not the guard)
        var act = () => handler.Handle(command, CancellationToken.None);

        // Assert — should not throw InvalidOperationException with SelfService message
        // It may succeed or throw a different error (e.g., missing schedule version), but not the SelfService guard
        try
        {
            await handler.Handle(command, CancellationToken.None);
        }
        catch (InvalidOperationException ex) when (ex.Message.Contains("SelfService"))
        {
            // This should NOT happen
            Assert.Fail("Should not throw SelfService guard error for AutoGenerated group.");
        }
        catch
        {
            // Other exceptions are acceptable (e.g., queue issues in test)
        }
    }
}
