using FluentAssertions;
using Jobuler.Application.Spaces.SpecialDays;
using Jobuler.Domain.Spaces;
using Jobuler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Jobuler.Tests.Application;

public class SpaceSpecialDayCommandTests
{
    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new AppDbContext(options);
    }

    [Fact]
    public async Task Create_ThenList_ReturnsSpecialDay()
    {
        await using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var date = new DateOnly(2026, 9, 22);

        var create = new CreateSpaceSpecialDayCommandHandler(db);
        var id = await create.Handle(new CreateSpaceSpecialDayCommand(
            spaceId,
            date,
            "Rosh Hashanah",
            SpaceSpecialDayKind.Holiday,
            2.5m,
            RequiresCoverage: true), CancellationToken.None);

        var list = new ListSpaceSpecialDaysQueryHandler(db);
        var result = await list.Handle(new ListSpaceSpecialDaysQuery(spaceId), CancellationToken.None);

        result.Should().ContainSingle();
        result[0].Id.Should().Be(id);
        result[0].Date.Should().Be(date);
        result[0].Name.Should().Be("Rosh Hashanah");
        result[0].Kind.Should().Be(SpaceSpecialDayKind.Holiday);
        result[0].HomeLeaveWeightMultiplier.Should().Be(2.5m);
        result[0].RequiresCoverage.Should().BeTrue();
    }

    [Fact]
    public async Task Create_DuplicateNameOnSameDate_IsRejected()
    {
        await using var db = CreateDb();
        var spaceId = Guid.NewGuid();
        var date = new DateOnly(2026, 9, 22);
        var handler = new CreateSpaceSpecialDayCommandHandler(db);

        await handler.Handle(new CreateSpaceSpecialDayCommand(
            spaceId,
            date,
            "Holiday",
            SpaceSpecialDayKind.Holiday,
            1.5m,
            RequiresCoverage: true), CancellationToken.None);

        var act = () => handler.Handle(new CreateSpaceSpecialDayCommand(
            spaceId,
            date,
            "Holiday",
            SpaceSpecialDayKind.Custom,
            1.5m,
            RequiresCoverage: true), CancellationToken.None);

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("A special day with this name already exists on this date.");
    }

    [Fact]
    public void IsraelHolidayCalendar_GeneratesKnown2026Dates()
    {
        var days = HolidayCalendarGenerator.Generate(
            "IL",
            2026,
            new HashSet<(DateOnly Date, string Name)>());

        days.Should().Contain(day => day.Name == "Passover" && day.Date == new DateOnly(2026, 4, 2));
        days.Should().Contain(day => day.Name == "Shavuot" && day.Date == new DateOnly(2026, 5, 22));
        days.Should().Contain(day => day.Name == "Rosh Hashanah" && day.Date == new DateOnly(2026, 9, 12));
        days.Should().Contain(day => day.Name == "Yom Kippur" && day.Date == new DateOnly(2026, 9, 21));
        days.Should().Contain(day => day.Name == "Sukkot" && day.Date == new DateOnly(2026, 9, 26));
    }

    [Fact]
    public async Task ImportHolidayCalendar_SkipsExistingDays()
    {
        await using var db = CreateDb();
        var spaceId = Guid.NewGuid();

        var create = new CreateSpaceSpecialDayCommandHandler(db);
        await create.Handle(new CreateSpaceSpecialDayCommand(
            spaceId,
            new DateOnly(2026, 9, 21),
            "Yom Kippur",
            SpaceSpecialDayKind.Holiday,
            3m,
            RequiresCoverage: true), CancellationToken.None);

        var import = new ImportHolidayCalendarCommandHandler(db);
        var result = await import.Handle(new ImportHolidayCalendarCommand(
            spaceId,
            "IL",
            2026), CancellationToken.None);

        result.Skipped.Should().ContainSingle(day =>
            day.Name == "Yom Kippur"
            && day.Date == new DateOnly(2026, 9, 21)
            && day.AlreadyExists);
        result.Imported.Should().OnlyContain(day => day.IsAutoGenerated);

        var list = new ListSpaceSpecialDaysQueryHandler(db);
        var days = await list.Handle(new ListSpaceSpecialDaysQuery(spaceId), CancellationToken.None);

        days.Where(day => day.Name == "Yom Kippur" && day.Date == new DateOnly(2026, 9, 21))
            .Should()
            .ContainSingle();
    }
}
