using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Jobuler.Application.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddSelfServiceScheduling : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "scheduling_mode",
                table: "groups",
                type: "text",
                nullable: false,
                defaultValue: "AutoGenerated");

            migrationBuilder.CreateTable(
                name: "scheduling_cycles",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    starts_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    ends_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    request_window_opens_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    request_window_closes_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    is_generated = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_scheduling_cycles", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "self_service_configs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    min_shifts_per_cycle = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    max_shifts_per_cycle = table.Column<int>(type: "integer", nullable: false, defaultValue: 7),
                    request_window_open_offset_hours = table.Column<int>(type: "integer", nullable: false, defaultValue: 168),
                    request_window_close_offset_hours = table.Column<int>(type: "integer", nullable: false, defaultValue: 24),
                    cancellation_cutoff_hours = table.Column<int>(type: "integer", nullable: false, defaultValue: 24),
                    waitlist_offer_minutes = table.Column<int>(type: "integer", nullable: false, defaultValue: 60),
                    cycle_duration_days = table.Column<int>(type: "integer", nullable: false, defaultValue: 7),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_self_service_configs", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "shift_requests",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    shift_slot_id = table.Column<Guid>(type: "uuid", nullable: false),
                    person_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    scheduling_cycle_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "text", nullable: false, defaultValue: "Pending"),
                    is_admin_override = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    processed_by_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    rejection_reason = table.Column<string>(type: "text", nullable: true),
                    cancellation_reason = table.Column<string>(type: "text", nullable: true),
                    cancelled_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_shift_requests", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "shift_slots",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_task_id = table.Column<Guid>(type: "uuid", nullable: false),
                    shift_template_id = table.Column<Guid>(type: "uuid", nullable: false),
                    scheduling_cycle_id = table.Column<Guid>(type: "uuid", nullable: false),
                    date = table.Column<DateOnly>(type: "date", nullable: false),
                    start_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    end_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    capacity = table.Column<int>(type: "integer", nullable: false),
                    current_fill_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    status = table.Column<string>(type: "text", nullable: false, defaultValue: "Open"),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_shift_slots", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "shift_templates",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_task_id = table.Column<Guid>(type: "uuid", nullable: false),
                    day_of_week = table.Column<int>(type: "integer", nullable: false),
                    start_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    end_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    required_headcount = table.Column<int>(type: "integer", nullable: false),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    created_by_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_shift_templates", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "swap_requests",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    initiator_person_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_person_id = table.Column<Guid>(type: "uuid", nullable: false),
                    initiator_shift_request_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_shift_request_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "text", nullable: false, defaultValue: "Pending"),
                    expires_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_swap_requests", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "waitlist_entries",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    space_id = table.Column<Guid>(type: "uuid", nullable: false),
                    shift_slot_id = table.Column<Guid>(type: "uuid", nullable: false),
                    person_id = table.Column<Guid>(type: "uuid", nullable: false),
                    position = table.Column<int>(type: "integer", nullable: false),
                    status = table.Column<string>(type: "text", nullable: false, defaultValue: "Waiting"),
                    offered_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    expires_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_waitlist_entries", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "idx_scheduling_cycles_group_dates",
                table: "scheduling_cycles",
                columns: new[] { "group_id", "starts_at", "ends_at" });

            migrationBuilder.CreateIndex(
                name: "IX_self_service_configs_group_id",
                table: "self_service_configs",
                column: "group_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "idx_shift_requests_no_dup",
                table: "shift_requests",
                columns: new[] { "shift_slot_id", "person_id" },
                unique: true,
                filter: "status IN ('Pending', 'Approved')");

            migrationBuilder.CreateIndex(
                name: "idx_shift_requests_person_cycle",
                table: "shift_requests",
                columns: new[] { "person_id", "scheduling_cycle_id", "status" });

            migrationBuilder.CreateIndex(
                name: "idx_shift_requests_slot",
                table: "shift_requests",
                columns: new[] { "shift_slot_id", "status" });

            migrationBuilder.CreateIndex(
                name: "idx_shift_slots_cycle",
                table: "shift_slots",
                columns: new[] { "scheduling_cycle_id", "status" });

            migrationBuilder.CreateIndex(
                name: "idx_shift_slots_group_date",
                table: "shift_slots",
                columns: new[] { "group_id", "date", "start_time" });

            migrationBuilder.CreateIndex(
                name: "IX_shift_slots_shift_template_id_date_group_id",
                table: "shift_slots",
                columns: new[] { "shift_template_id", "date", "group_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "idx_shift_templates_group",
                table: "shift_templates",
                column: "group_id",
                filter: "is_deleted = false");

            migrationBuilder.CreateIndex(
                name: "idx_swap_requests_status",
                table: "swap_requests",
                columns: new[] { "status", "expires_at" },
                filter: "status = 'Pending'");

            migrationBuilder.CreateIndex(
                name: "idx_waitlist_no_dup",
                table: "waitlist_entries",
                columns: new[] { "shift_slot_id", "person_id" },
                unique: true,
                filter: "status IN ('Waiting', 'Offered')");

            migrationBuilder.CreateIndex(
                name: "idx_waitlist_slot_position",
                table: "waitlist_entries",
                columns: new[] { "shift_slot_id", "position" },
                filter: "status = 'Waiting'");

            // RLS policies for tenant isolation on all new tables
            migrationBuilder.Sql(
                @"ALTER TABLE self_service_configs ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON self_service_configs
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE scheduling_cycles ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON scheduling_cycles
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE shift_templates ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON shift_templates
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE shift_slots ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON shift_slots
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE shift_requests ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON shift_requests
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE waitlist_entries ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON waitlist_entries
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");

            migrationBuilder.Sql(
                @"ALTER TABLE swap_requests ENABLE ROW LEVEL SECURITY;
                  CREATE POLICY tenant_isolation ON swap_requests
                  USING (space_id::text = current_setting('app.current_space_id', TRUE));");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop RLS policies before dropping tables
            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON swap_requests;
                  ALTER TABLE swap_requests DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON waitlist_entries;
                  ALTER TABLE waitlist_entries DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON shift_requests;
                  ALTER TABLE shift_requests DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON shift_slots;
                  ALTER TABLE shift_slots DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON shift_templates;
                  ALTER TABLE shift_templates DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON scheduling_cycles;
                  ALTER TABLE scheduling_cycles DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.Sql(
                @"DROP POLICY IF EXISTS tenant_isolation ON self_service_configs;
                  ALTER TABLE self_service_configs DISABLE ROW LEVEL SECURITY;");

            migrationBuilder.DropTable(
                name: "scheduling_cycles");

            migrationBuilder.DropTable(
                name: "self_service_configs");

            migrationBuilder.DropTable(
                name: "shift_requests");

            migrationBuilder.DropTable(
                name: "shift_slots");

            migrationBuilder.DropTable(
                name: "shift_templates");

            migrationBuilder.DropTable(
                name: "swap_requests");

            migrationBuilder.DropTable(
                name: "waitlist_entries");

            migrationBuilder.DropColumn(
                name: "scheduling_mode",
                table: "groups");
        }
    }
}
