using Jobuler.Domain.Spaces;

namespace Jobuler.Application.Spaces.SpecialDays;

public record SpaceSpecialDayDto(
    Guid Id,
    Guid SpaceId,
    DateOnly Date,
    string Name,
    SpaceSpecialDayKind Kind,
    decimal HomeLeaveWeightMultiplier,
    bool RequiresCoverage,
    bool IsAutoGenerated,
    DateTime CreatedAt,
    DateTime UpdatedAt);
