using Jobuler.Domain.Spaces;
using Jobuler.Infrastructure.Persistence;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Jobuler.Application.Spaces.SpecialDays;

public record CreateSpaceSpecialDayCommand(
    Guid SpaceId,
    DateOnly Date,
    string Name,
    SpaceSpecialDayKind Kind,
    decimal HomeLeaveWeightMultiplier,
    bool RequiresCoverage,
    bool IsAutoGenerated = false) : IRequest<Guid>;

public class CreateSpaceSpecialDayCommandHandler : IRequestHandler<CreateSpaceSpecialDayCommand, Guid>
{
    private readonly AppDbContext _db;

    public CreateSpaceSpecialDayCommandHandler(AppDbContext db) => _db = db;

    public async Task<Guid> Handle(CreateSpaceSpecialDayCommand request, CancellationToken ct)
    {
        await EnsureNameIsAvailableAsync(request.SpaceId, request.Date, request.Name, exceptId: null, ct);

        var day = SpaceSpecialDay.Create(
            request.SpaceId,
            request.Date,
            request.Name,
            request.Kind,
            request.HomeLeaveWeightMultiplier,
            request.RequiresCoverage,
            request.IsAutoGenerated);

        _db.SpaceSpecialDays.Add(day);
        await _db.SaveChangesAsync(ct);
        return day.Id;
    }

    private async Task EnsureNameIsAvailableAsync(
        Guid spaceId,
        DateOnly date,
        string name,
        Guid? exceptId,
        CancellationToken ct)
    {
        var normalizedName = name.Trim();
        var exists = await _db.SpaceSpecialDays.AsNoTracking()
            .AnyAsync(d => d.SpaceId == spaceId
                && d.Date == date
                && d.Name == normalizedName
                && (exceptId == null || d.Id != exceptId.Value), ct);

        if (exists)
            throw new InvalidOperationException("A special day with this name already exists on this date.");
    }
}

public record UpdateSpaceSpecialDayCommand(
    Guid SpaceId,
    Guid SpecialDayId,
    DateOnly Date,
    string Name,
    SpaceSpecialDayKind Kind,
    decimal HomeLeaveWeightMultiplier,
    bool RequiresCoverage) : IRequest;

public class UpdateSpaceSpecialDayCommandHandler : IRequestHandler<UpdateSpaceSpecialDayCommand>
{
    private readonly AppDbContext _db;

    public UpdateSpaceSpecialDayCommandHandler(AppDbContext db) => _db = db;

    public async Task Handle(UpdateSpaceSpecialDayCommand request, CancellationToken ct)
    {
        var day = await _db.SpaceSpecialDays
            .FirstOrDefaultAsync(d => d.Id == request.SpecialDayId && d.SpaceId == request.SpaceId, ct)
            ?? throw new KeyNotFoundException("Special day not found.");

        var normalizedName = request.Name.Trim();
        var exists = await _db.SpaceSpecialDays.AsNoTracking()
            .AnyAsync(d => d.SpaceId == request.SpaceId
                && d.Date == request.Date
                && d.Name == normalizedName
                && d.Id != request.SpecialDayId, ct);

        if (exists)
            throw new InvalidOperationException("A special day with this name already exists on this date.");

        day.Update(
            request.Date,
            request.Name,
            request.Kind,
            request.HomeLeaveWeightMultiplier,
            request.RequiresCoverage);

        await _db.SaveChangesAsync(ct);
    }
}

public record DeleteSpaceSpecialDayCommand(Guid SpaceId, Guid SpecialDayId) : IRequest;

public class DeleteSpaceSpecialDayCommandHandler : IRequestHandler<DeleteSpaceSpecialDayCommand>
{
    private readonly AppDbContext _db;

    public DeleteSpaceSpecialDayCommandHandler(AppDbContext db) => _db = db;

    public async Task Handle(DeleteSpaceSpecialDayCommand request, CancellationToken ct)
    {
        var day = await _db.SpaceSpecialDays
            .FirstOrDefaultAsync(d => d.Id == request.SpecialDayId && d.SpaceId == request.SpaceId, ct)
            ?? throw new KeyNotFoundException("Special day not found.");

        _db.SpaceSpecialDays.Remove(day);
        await _db.SaveChangesAsync(ct);
    }
}

public record ImportHolidayCalendarCommand(
    Guid SpaceId,
    string CountryCode,
    int Year) : IRequest<ImportHolidayCalendarResult>;

public class ImportHolidayCalendarCommandHandler
    : IRequestHandler<ImportHolidayCalendarCommand, ImportHolidayCalendarResult>
{
    private readonly AppDbContext _db;

    public ImportHolidayCalendarCommandHandler(AppDbContext db) => _db = db;

    public async Task<ImportHolidayCalendarResult> Handle(
        ImportHolidayCalendarCommand request,
        CancellationToken ct)
    {
        var from = new DateOnly(request.Year, 1, 1);
        var to = new DateOnly(request.Year, 12, 31);
        var existing = await _db.SpaceSpecialDays
            .Where(d => d.SpaceId == request.SpaceId && d.Date >= from && d.Date <= to)
            .ToListAsync(ct);

        var existingKeys = existing
            .Select(d => (d.Date, d.Name))
            .ToHashSet();

        var preview = HolidayCalendarGenerator.Generate(
            request.CountryCode,
            request.Year,
            existingKeys);

        var skipped = preview.Where(day => day.AlreadyExists).ToList();
        var imported = new List<SpaceSpecialDay>();

        foreach (var day in preview.Where(day => !day.AlreadyExists))
        {
            var entity = SpaceSpecialDay.Create(
                request.SpaceId,
                day.Date,
                day.Name,
                day.Kind,
                day.HomeLeaveWeightMultiplier,
                day.RequiresCoverage,
                isAutoGenerated: true);

            _db.SpaceSpecialDays.Add(entity);
            imported.Add(entity);
        }

        await _db.SaveChangesAsync(ct);

        return new ImportHolidayCalendarResult(
            imported
                .OrderBy(d => d.Date)
                .ThenBy(d => d.Name)
                .Select(d => new SpaceSpecialDayDto(
                    d.Id,
                    d.SpaceId,
                    d.Date,
                    d.Name,
                    d.Kind,
                    d.HomeLeaveWeightMultiplier,
                    d.RequiresCoverage,
                    d.IsAutoGenerated,
                    d.CreatedAt,
                    d.UpdatedAt))
                .ToList(),
            skipped);
    }
}
