using Jobuler.Infrastructure.Persistence;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Jobuler.Application.Spaces.SpecialDays;

public record ListSpaceSpecialDaysQuery(
    Guid SpaceId,
    DateOnly? From = null,
    DateOnly? To = null) : IRequest<IReadOnlyList<SpaceSpecialDayDto>>;

public class ListSpaceSpecialDaysQueryHandler
    : IRequestHandler<ListSpaceSpecialDaysQuery, IReadOnlyList<SpaceSpecialDayDto>>
{
    private readonly AppDbContext _db;

    public ListSpaceSpecialDaysQueryHandler(AppDbContext db) => _db = db;

    public async Task<IReadOnlyList<SpaceSpecialDayDto>> Handle(
        ListSpaceSpecialDaysQuery request,
        CancellationToken ct)
    {
        var query = _db.SpaceSpecialDays
            .AsNoTracking()
            .Where(d => d.SpaceId == request.SpaceId);

        if (request.From.HasValue)
            query = query.Where(d => d.Date >= request.From.Value);

        if (request.To.HasValue)
            query = query.Where(d => d.Date <= request.To.Value);

        return await query
            .OrderBy(d => d.Date)
            .ThenBy(d => d.Name)
            .Select(d => new SpaceSpecialDayDto(
                d.Id,
                d.SpaceId,
                d.Date,
                d.Name,
                d.Kind,
                d.HomeLeaveWeightMultiplier,
                d.RequiresCoverage,
                d.IsAutoGenerated,
                d.CreatedAt,
                d.UpdatedAt))
            .ToListAsync(ct);
    }
}
