using Jobuler.Infrastructure.Persistence;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Jobuler.Application.Spaces.SpecialDays;

public record ListSpaceSpecialDaysQuery(
    Guid SpaceId,
    DateOnly? From = null,
    DateOnly? To = null) : IRequest<IReadOnlyList<SpaceSpecialDayDto>>;

public class ListSpaceSpecialDaysQueryHandler
    : IRequestHandler<ListSpaceSpecialDaysQuery, IReadOnlyList<SpaceSpecialDayDto>>
{
    private readonly AppDbContext _db;

    public ListSpaceSpecialDaysQueryHandler(AppDbContext db) => _db = db;

    public async Task<IReadOnlyList<SpaceSpecialDayDto>> Handle(
        ListSpaceSpecialDaysQuery request,
        CancellationToken ct)
    {
        var query = _db.SpaceSpecialDays
            .AsNoTracking()
            .Where(d => d.SpaceId == request.SpaceId);

        if (request.From.HasValue)
            query = query.Where(d => d.Date >= request.From.Value);

        if (request.To.HasValue)
            query = query.Where(d => d.Date <= request.To.Value);

        return await query
            .OrderBy(d => d.Date)
            .ThenBy(d => d.Name)
            .Select(d => new SpaceSpecialDayDto(
                d.Id,
                d.SpaceId,
                d.Date,
                d.Name,
                d.Kind,
                d.HomeLeaveWeightMultiplier,
                d.RequiresCoverage,
                d.IsAutoGenerated,
                d.CreatedAt,
                d.UpdatedAt))
            .ToListAsync(ct);
    }
}

public record PreviewHolidayCalendarQuery(
    Guid SpaceId,
    string CountryCode,
    int Year) : IRequest<IReadOnlyList<HolidayCalendarDayDto>>;

public class PreviewHolidayCalendarQueryHandler
    : IRequestHandler<PreviewHolidayCalendarQuery, IReadOnlyList<HolidayCalendarDayDto>>
{
    private readonly AppDbContext _db;

    public PreviewHolidayCalendarQueryHandler(AppDbContext db) => _db = db;

    public async Task<IReadOnlyList<HolidayCalendarDayDto>> Handle(
        PreviewHolidayCalendarQuery request,
        CancellationToken ct)
    {
        var from = new DateOnly(request.Year, 1, 1);
        var to = new DateOnly(request.Year, 12, 31);
        var existing = await _db.SpaceSpecialDays
            .AsNoTracking()
            .Where(d => d.SpaceId == request.SpaceId && d.Date >= from && d.Date <= to)
            .Select(d => new { d.Date, d.Name })
            .ToListAsync(ct);

        return HolidayCalendarGenerator.Generate(
            request.CountryCode,
            request.Year,
            existing.Select(d => (d.Date, d.Name)).ToHashSet());
    }
}
