import { apiClient } from "./client";

export type SpaceSpecialDayKind = "Holiday" | "Weekend" | "Custom";

export interface SpaceSpecialDayDto {
  id: string;
  spaceId: string;
  date: string;
  name: string;
  kind: SpaceSpecialDayKind;
  homeLeaveWeightMultiplier: number;
  requiresCoverage: boolean;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SaveSpaceSpecialDayPayload {
  date: string;
  name: string;
  kind: SpaceSpecialDayKind;
  homeLeaveWeightMultiplier: number;
  requiresCoverage: boolean;
}

export async function listSpaceSpecialDays(
  spaceId: string,
  from?: string,
  to?: string
): Promise<SpaceSpecialDayDto[]> {
  const { data } = await apiClient.get(`/spaces/${spaceId}/special-days`, {
    params: { from, to },
  });
  return data;
}

export async function createSpaceSpecialDay(
  spaceId: string,
  payload: SaveSpaceSpecialDayPayload
): Promise<{ id: string }> {
  const { data } = await apiClient.post(`/spaces/${spaceId}/special-days`, payload);
  return data;
}

export async function updateSpaceSpecialDay(
  spaceId: string,
  specialDayId: string,
  payload: SaveSpaceSpecialDayPayload
): Promise<void> {
  await apiClient.put(`/spaces/${spaceId}/special-days/${specialDayId}`, payload);
}

export async function deleteSpaceSpecialDay(
  spaceId: string,
  specialDayId: string
): Promise<void> {
  await apiClient.delete(`/spaces/${spaceId}/special-days/${specialDayId}`);
}
