-- Migration 084: Align SQL self-service schema with EF model
-- The original SQL migration 077 created an early self-service draft schema.
-- This migration adds the EF-backed columns/tables used by the current API while
-- keeping the older columns in place for idempotent local upgrades.

-- Groups
ALTER TABLE groups
  ADD COLUMN IF NOT EXISTS scheduling_mode TEXT NOT NULL DEFAULT 'AutoGenerated';

-- Self-service config
CREATE TABLE IF NOT EXISTS self_service_configs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE self_service_configs
  ADD COLUMN IF NOT EXISTS min_shifts_per_cycle INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_shifts_per_cycle INTEGER NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS request_window_open_offset_hours INTEGER NOT NULL DEFAULT 168,
  ADD COLUMN IF NOT EXISTS request_window_close_offset_hours INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS cancellation_cutoff_hours INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS max_late_cancellations_per_cycle INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS late_cancellation_window_hours INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS waitlist_offer_minutes INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS cycle_duration_days INTEGER NOT NULL DEFAULT 7;

CREATE UNIQUE INDEX IF NOT EXISTS ix_self_service_configs_group_id
  ON self_service_configs(group_id);

-- Scheduling cycles
CREATE TABLE IF NOT EXISTS scheduling_cycles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  request_window_opens_at TIMESTAMPTZ NOT NULL,
  request_window_closes_at TIMESTAMPTZ NOT NULL,
  is_generated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scheduling_cycles_group_dates
  ON scheduling_cycles(group_id, starts_at, ends_at);

-- Shift templates
CREATE TABLE IF NOT EXISTS shift_templates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL,
  group_task_id UUID,
  day_of_week INTEGER,
  start_time TIME,
  end_time TIME,
  required_headcount INTEGER,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_by_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE shift_templates
  ADD COLUMN IF NOT EXISTS group_task_id UUID,
  ADD COLUMN IF NOT EXISTS day_of_week INTEGER,
  ADD COLUMN IF NOT EXISTS start_time TIME,
  ADD COLUMN IF NOT EXISTS end_time TIME,
  ADD COLUMN IF NOT EXISTS required_headcount INTEGER,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_by_user_id UUID;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_templates' AND column_name = 'starts_at_time'
  ) THEN
    EXECUTE '
      UPDATE shift_templates
      SET start_time = COALESCE(start_time, starts_at_time)
      WHERE start_time IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_templates' AND column_name = 'ends_at_time'
  ) THEN
    EXECUTE '
      UPDATE shift_templates
      SET end_time = COALESCE(end_time, ends_at_time)
      WHERE end_time IS NULL';
  END IF;

  UPDATE shift_templates
  SET
    required_headcount = COALESCE(required_headcount, 1),
    day_of_week = COALESCE(day_of_week, 0);

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_templates' AND column_name = 'name'
  ) THEN
    EXECUTE '
      UPDATE shift_templates st
      SET group_task_id = t.id
      FROM tasks t
      WHERE st.group_task_id IS NULL
        AND t.group_id = st.group_id
        AND t.name = st.name';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_shift_templates_group
  ON shift_templates(group_id)
  WHERE is_deleted = FALSE;

-- Shift slots
CREATE TABLE IF NOT EXISTS shift_slots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL,
  group_task_id UUID,
  shift_template_id UUID,
  scheduling_cycle_id UUID,
  date DATE,
  start_time TIME,
  end_time TIME,
  capacity INTEGER,
  current_fill_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE shift_slots
  ADD COLUMN IF NOT EXISTS group_task_id UUID,
  ADD COLUMN IF NOT EXISTS shift_template_id UUID,
  ADD COLUMN IF NOT EXISTS scheduling_cycle_id UUID,
  ADD COLUMN IF NOT EXISTS date DATE,
  ADD COLUMN IF NOT EXISTS start_time TIME,
  ADD COLUMN IF NOT EXISTS end_time TIME,
  ADD COLUMN IF NOT EXISTS capacity INTEGER,
  ADD COLUMN IF NOT EXISTS current_fill_count INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'cycle_id'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET scheduling_cycle_id = COALESCE(scheduling_cycle_id, cycle_id)
      WHERE scheduling_cycle_id IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'template_id'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET shift_template_id = COALESCE(shift_template_id, template_id)
      WHERE shift_template_id IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'starts_at'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET
        date = COALESCE(date, starts_at::date),
        start_time = COALESCE(start_time, starts_at::time)
      WHERE date IS NULL OR start_time IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'ends_at'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET end_time = COALESCE(end_time, ends_at::time)
      WHERE end_time IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'max_headcount'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET capacity = COALESCE(capacity, max_headcount)
      WHERE capacity IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'required_headcount'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET capacity = COALESCE(capacity, required_headcount)
      WHERE capacity IS NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'shift_slots' AND column_name = 'current_headcount'
  ) THEN
    EXECUTE '
      UPDATE shift_slots
      SET current_fill_count = COALESCE(current_fill_count, current_headcount, 0)';
  END IF;

  UPDATE shift_slots
  SET capacity = COALESCE(capacity, 1);

  UPDATE shift_slots ss
  SET group_task_id = st.group_task_id
  FROM shift_templates st
  WHERE ss.group_task_id IS NULL
    AND ss.shift_template_id = st.id;
END $$;

CREATE INDEX IF NOT EXISTS idx_shift_slots_cycle
  ON shift_slots(scheduling_cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_shift_slots_group_date
  ON shift_slots(group_id, date, start_time);

CREATE UNIQUE INDEX IF NOT EXISTS idx_shift_slots_template_date_group
  ON shift_slots(shift_template_id, date, group_id)
  WHERE shift_template_id IS NOT NULL AND date IS NOT NULL;

-- Shift requests
CREATE TABLE IF NOT EXISTS shift_requests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  shift_slot_id UUID NOT NULL,
  person_id UUID NOT NULL,
  group_id UUID,
  scheduling_cycle_id UUID,
  status TEXT NOT NULL DEFAULT 'Pending',
  is_admin_override BOOLEAN NOT NULL DEFAULT FALSE,
  processed_by_user_id UUID,
  rejection_reason TEXT,
  cancellation_reason TEXT,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE shift_requests
  ADD COLUMN IF NOT EXISTS group_id UUID,
  ADD COLUMN IF NOT EXISTS scheduling_cycle_id UUID,
  ADD COLUMN IF NOT EXISTS is_admin_override BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS processed_by_user_id UUID,
  ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;

UPDATE shift_requests sr
SET
  group_id = COALESCE(sr.group_id, ss.group_id),
  scheduling_cycle_id = COALESCE(sr.scheduling_cycle_id, ss.scheduling_cycle_id)
FROM shift_slots ss
WHERE sr.shift_slot_id = ss.id
  AND (sr.group_id IS NULL OR sr.scheduling_cycle_id IS NULL);

CREATE INDEX IF NOT EXISTS idx_shift_requests_person_cycle
  ON shift_requests(person_id, scheduling_cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_shift_requests_slot
  ON shift_requests(shift_slot_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_shift_requests_no_dup
  ON shift_requests(shift_slot_id, person_id)
  WHERE status IN ('Pending', 'Approved');

-- Waitlist and swaps
CREATE TABLE IF NOT EXISTS waitlist_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  shift_slot_id UUID NOT NULL,
  person_id UUID NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Waiting',
  offered_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_waitlist_no_dup
  ON waitlist_entries(shift_slot_id, person_id)
  WHERE status IN ('Waiting', 'Offered');

CREATE INDEX IF NOT EXISTS idx_waitlist_slot_position
  ON waitlist_entries(shift_slot_id, position)
  WHERE status = 'Waiting';

CREATE TABLE IF NOT EXISTS swap_requests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID,
  initiator_person_id UUID,
  target_person_id UUID,
  initiator_shift_request_id UUID,
  target_shift_request_id UUID,
  status TEXT NOT NULL DEFAULT 'Pending',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE swap_requests
  ADD COLUMN IF NOT EXISTS group_id UUID,
  ADD COLUMN IF NOT EXISTS initiator_person_id UUID,
  ADD COLUMN IF NOT EXISTS target_person_id UUID,
  ADD COLUMN IF NOT EXISTS initiator_shift_request_id UUID,
  ADD COLUMN IF NOT EXISTS target_shift_request_id UUID;

CREATE INDEX IF NOT EXISTS idx_swap_requests_status
  ON swap_requests(status, expires_at)
  WHERE status = 'Pending';

-- Review queues
CREATE TABLE IF NOT EXISTS shift_absence_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL,
  scheduling_cycle_id UUID NOT NULL,
  shift_request_id UUID NOT NULL,
  shift_slot_id UUID NOT NULL,
  person_id UUID NOT NULL,
  reason VARCHAR(500) NOT NULL,
  is_late BOOLEAN NOT NULL DEFAULT FALSE,
  reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'Pending',
  reviewed_by_user_id UUID,
  admin_note VARCHAR(500),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shift_absence_reports_group_status
  ON shift_absence_reports(group_id, status, reported_at);

CREATE INDEX IF NOT EXISTS idx_shift_absence_reports_person_cycle
  ON shift_absence_reports(person_id, scheduling_cycle_id, is_late, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_shift_absence_reports_shift_request
  ON shift_absence_reports(shift_request_id);

CREATE TABLE IF NOT EXISTS shift_change_requests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  space_id UUID NOT NULL,
  group_id UUID NOT NULL,
  scheduling_cycle_id UUID NOT NULL,
  shift_request_id UUID NOT NULL,
  original_shift_slot_id UUID NOT NULL,
  requested_shift_slot_id UUID,
  person_id UUID NOT NULL,
  reason VARCHAR(500) NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_by_user_id UUID,
  admin_note VARCHAR(500),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shift_change_requests_group_status
  ON shift_change_requests(group_id, status, requested_at);

CREATE INDEX IF NOT EXISTS idx_shift_change_requests_person_cycle
  ON shift_change_requests(person_id, scheduling_cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_shift_change_requests_requested_slot
  ON shift_change_requests(requested_shift_slot_id);

CREATE INDEX IF NOT EXISTS idx_shift_change_requests_shift_request_pending
  ON shift_change_requests(shift_request_id)
  WHERE status = 'Pending';

-- RLS
ALTER TABLE self_service_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduling_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE waitlist_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE swap_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_absence_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_change_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON self_service_configs;
DROP POLICY IF EXISTS tenant_isolation ON scheduling_cycles;
DROP POLICY IF EXISTS tenant_isolation ON shift_templates;
DROP POLICY IF EXISTS tenant_isolation ON shift_slots;
DROP POLICY IF EXISTS tenant_isolation ON shift_requests;
DROP POLICY IF EXISTS tenant_isolation ON waitlist_entries;
DROP POLICY IF EXISTS tenant_isolation ON swap_requests;
DROP POLICY IF EXISTS tenant_isolation ON shift_absence_reports;
DROP POLICY IF EXISTS tenant_isolation ON shift_change_requests;

CREATE POLICY tenant_isolation ON self_service_configs
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON scheduling_cycles
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON shift_templates
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON shift_slots
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON shift_requests
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON waitlist_entries
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON swap_requests
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON shift_absence_reports
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
CREATE POLICY tenant_isolation ON shift_change_requests
  USING (space_id::text = current_setting('app.current_space_id', TRUE));
