using Jobuler.Domain.Spaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Jobuler.Infrastructure.Persistence.Configurations;

public class SpaceSpecialDayConfiguration : IEntityTypeConfiguration<SpaceSpecialDay>
{
    public void Configure(EntityTypeBuilder<SpaceSpecialDay> builder)
    {
        builder.ToTable("space_special_days");
        builder.HasKey(d => d.Id);
        builder.Property(d => d.Id).HasColumnName("id");
        builder.Property(d => d.SpaceId).HasColumnName("space_id");
        builder.Property(d => d.Date).HasColumnName("date").HasColumnType("date");
        builder.Property(d => d.Name).HasColumnName("name").HasMaxLength(120).IsRequired();
        builder.Property(d => d.Kind).HasColumnName("kind").HasConversion<int>();
        builder.Property(d => d.HomeLeaveWeightMultiplier)
            .HasColumnName("home_leave_weight_multiplier")
            .HasPrecision(3, 2);
        builder.Property(d => d.RequiresCoverage).HasColumnName("requires_coverage");
        builder.Property(d => d.IsAutoGenerated).HasColumnName("is_auto_generated");
        builder.Property(d => d.CreatedAt).HasColumnName("created_at");
        builder.Property(d => d.UpdatedAt).HasColumnName("updated_at");

        builder.HasIndex(d => new { d.SpaceId, d.Date, d.Name })
            .IsUnique()
            .HasDatabaseName("IX_space_special_days_space_date_name");
    }
}
