"use client";

import { useEffect, useRef, useState, Suspense } from "react";
import { useTranslations } from "next-intl";
import AppShell from "@/components/shell/AppShell";
import { useSpaceStore } from "@/lib/store/spaceStore";
import { useRouter, useSearchParams } from "next/navigation";
import { getAvatarColor, getAvatarLetter } from "@/lib/utils/groupAvatar";
import { useGroups, useDeletedGroups, useCreateGroup, useRestoreGroup } from "@/lib/query/hooks/useGroups";
import Modal from "@/components/Modal";
import GroupTemplatePicker from "@/components/GroupTemplatePicker";
import CreateGroupWizard from "@/components/CreateGroupWizard";
import { ONBOARDING_STEPS } from "@/lib/onboarding/steps";
import { useOnboardingStore } from "@/lib/store/onboardingStore";
import { getCurrentStepIndex } from "@/lib/onboarding/decisions";
import { useWriteGuard } from "@/lib/api/writeGuard";
import { apiClient } from "@/lib/api/client";
import type { SchedulingMode } from "@/components/groups/selfService/SchedulingModeSelector";

export default function GroupsPageWrapper() {
  return (
    <Suspense fallback={null}>
      <GroupsPage />
    </Suspense>
  );
}

function GroupsPage() {
  const t = useTranslations("groups");
  const tErrors = useTranslations("errors");
  const tCommon = useTranslations("common");
  const { currentSpaceId } = useSpaceStore();
  const router = useRouter();
  const searchParams = useSearchParams();
  const deletedRef = useRef<HTMLDivElement>(null);

  const [createError, setCreateError] = useState<string | null>(null);
  const [templateGroupId, setTemplateGroupId] = useState<string | null>(null);
  const [showCreateWizard, setShowCreateWizard] = useState(false);

  const tOnboarding = useTranslations("onboarding");
  const { steps: onboardingSteps } = useOnboardingStore();
  const currentStepIndex = getCurrentStepIndex(onboardingSteps);

  const { isDisabled: writeGuardDisabled, tooltipText: writeGuardTooltip } = useWriteGuard();

  const { data: groups = [], isLoading: loading, isError: groupsError } = useGroups(currentSpaceId);
  const { data: deletedGroups = [], isLoading: deletedLoading } = useDeletedGroups(currentSpaceId);
  const createGroup = useCreateGroup(currentSpaceId);
  const restoreGroup = useRestoreGroup(currentSpaceId);

  // Scroll to deleted section if ?tab=deleted
  useEffect(() => {
    if (searchParams.get("tab") === "deleted" && deletedRef.current && !deletedLoading) {
      setTimeout(() => deletedRef.current?.scrollIntoView({ behavior: "smooth" }), 300);
    }
  }, [searchParams, deletedLoading]);

  async function handleCreateWithWizard(name: string, templateId: string, schedulingMode?: SchedulingMode) {
    if (!currentSpaceId) return;
    setCreateError(null);
    try {
      const result = await createGroup.mutateAsync(name);
      const newGroupId = (result as { data?: { id?: string } })?.data?.id;
      if (newGroupId) {
        // Set scheduling mode if specified (defaults to AutoGenerated on backend)
        if (schedulingMode && schedulingMode !== "AutoGenerated") {
          await apiClient.put(`/spaces/${currentSpaceId}/groups/${newGroupId}/scheduling-mode`, {
            mode: schedulingMode,
          });
        }
        setShowCreateWizard(false);
        // Always redirect to the new group — template settings can be configured there
        router.push(`/groups/${newGroupId}`);
      }
    } catch (err: unknown) {
      // Don't show error on the page — the wizard modal handles its own error display
      throw err; // re-throw so the wizard knows it failed
    }
  }

  async function handleRestore(id: string) {
    if (!currentSpaceId) return;
    try {
      await restoreGroup.mutateAsync(id);
    } catch { /* non-fatal */ }
  }

  return (
    <AppShell>
      <div className="max-w-4xl space-y-5 sm:space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-slate-900">{t("title")}</h1>
            <p className="text-xs sm:text-sm text-slate-500 mt-1">{t("subtitle")}</p>
          </div>
        </div>

        {/* Create group button — only show when API is working */}
        {!groupsError && (
          <span title={writeGuardDisabled ? writeGuardTooltip : undefined}>
            <button
              type="button"
              onClick={() => setShowCreateWizard(true)}
              disabled={writeGuardDisabled}
              className="bg-sky-500 hover:bg-sky-600 text-white text-sm font-medium px-4 py-2.5 rounded-xl transition-colors whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {t("newGroup")}
            </button>
          </span>
        )}

        {createError && <p className="text-sm text-red-600">{createError}</p>}

        {/* Active groups */}
        {loading ? (
          <p className="text-slate-400 text-sm py-8">{tCommon("loading")}</p>
        ) : groups.length === 0 ? (
          <div className="bg-white rounded-xl border border-slate-200 p-6 space-y-5">
            <div className="flex flex-col items-center text-center">
              <svg className="w-10 h-10 text-slate-200 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              <p className="text-slate-400 text-sm">{t("noGroups")}</p>
            </div>

            {/* Inline onboarding steps */}
            <div className="border-t border-slate-100 pt-4">
              <h3 className="text-sm font-semibold text-slate-700 mb-3">{tOnboarding("title")}</h3>
              <ol className="space-y-2">
                {ONBOARDING_STEPS.map((step, index) => {
                  const isCompleted = onboardingSteps[step.key];
                  const isCurrent = index === currentStepIndex;
                  return (
                    <li key={step.key} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 ${isCurrent ? "bg-sky-50 border border-sky-200" : ""}`}>
                      <div className={`flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                        isCompleted ? "bg-green-100 text-green-600" : isCurrent ? "bg-sky-500 text-white" : "bg-slate-100 text-slate-400"
                      }`}>
                        {isCompleted ? (
                          <svg width="12" height="12" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                        ) : (
                          index + 1
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className={`text-sm ${isCompleted ? "text-slate-400 line-through" : isCurrent ? "font-medium text-slate-900" : "text-slate-600"}`}>
                          {tOnboarding(`steps.${step.key}.title`)}
                        </p>
                        {isCurrent && (
                          <p className="text-xs text-slate-500 mt-0.5">{tOnboarding(`steps.${step.key}.description`)}</p>
                        )}
                      </div>
                    </li>
                  );
                })}
              </ol>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">
            {groups.map(g => {
              // Determine parent/child relationships
              const parentGroup = g.parentGroupId ? groups.find(p => p.id === g.parentGroupId) : null;
              const childGroups = groups.filter(c => c.parentGroupId === g.id);

              return (
                <button
                  key={g.id}
                  onClick={() => router.push(`/groups/${g.id}`)}
                  aria-label={`${g.name} — ${g.memberCount} ${t("members")}`}
                  className="text-start bg-white border border-slate-200 rounded-2xl p-5 hover:border-sky-300 hover:shadow-md transition-all group"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div
                      className="w-10 h-10 rounded-xl flex items-center justify-center text-white text-base font-bold flex-shrink-0"
                      style={{ background: getAvatarColor(g.name) }}
                    >
                      {getAvatarLetter(g.name)}
                    </div>
                    <svg className="w-4 h-4 text-slate-300 group-hover:text-sky-400 transition-colors mt-1 rtl:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                    </svg>
                  </div>
                  <h2 className="text-base font-semibold text-slate-900">{g.name}</h2>
                  <p className="text-xs text-slate-400 mt-1">{g.memberCount} {t("members")}</p>
                  {/* Parent/child relationship indicators */}
                  {parentGroup && (
                    <p className="text-xs text-sky-600 dark:text-sky-400 mt-1.5 flex items-center gap-1">
                      <svg className="w-3 h-3 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 10l7-7m0 0l7 7m-7-7v18" />
                      </svg>
                      {t("childOf")}: {parentGroup.name}
                    </p>
                  )}
                  {childGroups.length > 0 && (
                    <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-1.5 flex items-center gap-1">
                      <svg className="w-3 h-3 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                      </svg>
                      {t("parentOf")}: {childGroups.map(c => c.name).join(", ")}
                    </p>
                  )}
                </button>
              );
            })}
          </div>
        )}

        {/* Deleted groups */}
        <div ref={deletedRef} className="border-t border-slate-100 pt-6">
          <h2 className="text-base font-semibold text-slate-700 mb-3">{t("deletedGroups")}</h2>
          {deletedLoading ? (
            <p className="text-sm text-slate-400">{tCommon("loading")}</p>
          ) : deletedGroups.length === 0 ? (
            <p className="text-sm text-slate-400">{t("noDeletedGroups")}</p>
          ) : (
            <div className="space-y-2">
              {deletedGroups.map(g => (
                <div key={g.id} className="flex items-center justify-between bg-white border border-slate-200 rounded-xl px-4 py-3">
                  <span className="text-sm text-slate-700">{g.name}</span>
                  <button
                    onClick={() => handleRestore(g.id)}
                    disabled={restoreGroup.isPending}
                    className="text-xs text-sky-600 border border-sky-200 hover:bg-sky-50 px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50"
                  >
                    {t("restore")}
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Create group wizard modal */}
      <CreateGroupWizard
        open={showCreateWizard}
        onClose={() => setShowCreateWizard(false)}
        onCreateGroup={handleCreateWithWizard}
        isPending={createGroup.isPending}
      />

      {/* Template picker modal — shown after creating a new group with a non-custom template */}
      {templateGroupId && currentSpaceId && (
        <Modal
          open={true}
          onClose={() => { setTemplateGroupId(null); router.push(`/groups/${templateGroupId}`); }}
          title={t("templates.title")}
          maxWidth={600}
        >
          <GroupTemplatePicker
            spaceId={currentSpaceId}
            groupId={templateGroupId}
            onComplete={() => { setTemplateGroupId(null); router.push(`/groups/${templateGroupId}`); }}
            onSkip={() => { setTemplateGroupId(null); router.push(`/groups/${templateGroupId}`); }}
          />
        </Modal>
      )}
    </AppShell>
  );
}
